spring.application.name=Todo-Rest-API

# In Memory DB config
spring.h2.console.enabled = true
spring.h2.console.path = /h2

#DB Config
spring.datasource.url = jdbc:h2:mem:tododb
spring.datasource.driverClassName = org.h2.Driver
spring.datasource.username = sa
spring.datasource.password=

# ORM Config
spring.jpa.hibernate.ddl-auto = update

# Security Config
spring.security.user.name = Kavin
spring.security.user.password = 1234

# Logging Config
logging.level.root = info